# Generated by Django 3.1.4 on 2022-11-03 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='documents',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='case.cases', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case.documentstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case.documenttypes', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='cases',
            name='authority',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='case.taxauthorities', verbose_name='Налоговый орган'),
        ),
        migrations.AddField(
            model_name='cases',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Налоговый инспектор'),
        ),
        migrations.AddField(
            model_name='cases',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_payer', to=settings.AUTH_USER_MODEL, verbose_name='Налогоплательщик'),
        ),
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.casestatus', verbose_name='Статус экспертизы'),
        ),
        migrations.AddField(
            model_name='cases',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='case.themes', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='cases',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_type', to='case.projecttypes', verbose_name='Тип проекта'),
        ),
    ]
